Update patch set 6
Patch Set 6: Code-Review-1

I think the dci-api/Dockerfile is missing.

>  Building api
>  ERROR: Cannot locate specified Dockerfile: Dockerfile

Patch-set: 6