docker: increase HTTP timeout
We have some failure on the gate due to HTTP timeout during the boot
of docker vms.

ERROR: for db  UnixHTTPConnectionPool(host='localhost', port=None):
Read timed out. (read timeout=60)

Try to increase it to 180 seconds.

Change-Id: I05ba9a459572951211e3b6dd80bbc76c2076cdec